Models/Class.cs
namespace P013AspNetMVCEgitim.Models
{
	public class Adres
	{
		public int Id { get; set; }
		public string Sehir { get; set; }
		public string Ilce { get; set; }
		public string AcikAdres { get; set; }

	}
}

Models/ErrorViewModel.cs
namespace P013AspNetMVCEgitim.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Kullanici.cs
namespace P013AspNetMVCEgitim.Models
{
	public class Kullanici
	{
		public int Id { get; set; }

		public string Ad { get; set; }

		public string Soyad { get; set; }

		public string Email { get; set; }

		public string KullaniciAdi { get; set; }

		public string Sifre { get; set; }

	}
}

Models/UyeSayfasiViewModel.cs
namespace P013AspNetMVCEgitim.Models
{
    public class UyeSayfasiViewModel
    {
        public Kullanici Kullanici { get; set; }
        public Adres Adres { get; set; }

    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using P013AspNetMVCEgitim.Models;
using System.Diagnostics;

namespace P013AspNetMVCEgitim.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        [HttpGet] // varsayılan değer GET tir
		public IActionResult ContactUs()
		{
			return View();
		}
        [HttpPost]
		public IActionResult ContactUs(string ad)
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MVC01RazorSyntaxController.cs
using Microsoft.AspNetCore.Mvc;

namespace P013AspNetMVCEgitim.Controllers
{
	public class MVC01RazorSyntaxController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

Controllers/MVC02HtmlAndTagHelpersController.cs
using Microsoft.AspNetCore.Mvc;

namespace P013AspNetMVCEgitim.Controllers
{
    public class MVC02HtmlAndTagHelpersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/MVC03DataTransferController.cs
using Microsoft.AspNetCore.Mvc;

namespace P013AspNetMVCEgitim.Controllers
{
	public class MVC03DataTransferController : Controller
	{
		public IActionResult Index(string Ara) // get metoduyla 
		{
			// Mvc de temel olarak 3 farklı yöntemle ekrana veri gönderebiliriz

			// 1-ViewBag : Tek kullanımlık ömrü var
			ViewBag.UrunKategorisi = "Bilgisayar";
			// 2-ViewData : Tek kullanımlık ömrü var
			ViewData["ÜrünAdi"] = "Asus Dizüstü Bilgisayar";
			// 3-TempData : İki kullanımlık ömrü var
			TempData["UrunFiyatı"] = 9999;

			ViewBag.GetVerisi = Ara;

			return View();
		}
		[HttpPost] //aşağıdaki metod post işleminde çalışsın
		public IActionResult Index (string text1, string ddlListe, bool cbOnay, IFormCollection formCollection)
		{
			ViewBag.Yontem1 = "1. Yöntem(Parametrelerden gelen veriler)";
			ViewBag.Mesaj = "Textbox dan gelen veri : " + text1;
			ViewData["MesajListe"] = "ddlListe dan gelen veri : " + ddlListe;
			TempData["Tdata"] = "cbOnay dan gelen değer : " + cbOnay;

			ViewBag.Yontem2 = "2. Yöntem(IFormCollection)";
			ViewBag.Mesaj2 = "Textbox dan gelen veri : " + formCollection ["text1"];
			ViewData["MesajListe2"] = "ddlListe dan gelen veri : " + formCollection["ddlListe"];
			TempData["Tdata2"] = "cbOnay dan gelen değer : " + formCollection["cbOnay"][0];

			ViewBag.Yontem3 = "3. Yöntem(RequestForm)";
			ViewBag.Mesaj3 = "Textbox dan gelen veri : " + Request.Form["text1"];
			ViewData["MesajListe3"] = "ddlListe dan gelen veri : " + Request.Form["ddlListe"];
			TempData["Tdata3"] = "cbOnay dan gelen değer : " + Request.Form["cbOnay"][0];

			return View();
		}
	}
}

Controllers/MVC04ModelBindingController.cs
using Microsoft.AspNetCore.Mvc;
using P013AspNetMVCEgitim.Models;

namespace P013AspNetMVCEgitim.Controllers
{
	public class MVC04ModelBindingController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult KullaniciDetay()
		{
			Kullanici kullanici = new();
			kullanici.KullaniciAdi = "Admin";
			kullanici.Ad = "Murat";
            kullanici.Soyad = "Yılmaz";
            kullanici.Sifre = "123";
            kullanici.Email = "Murat@yilmaz.co";
            return View(kullanici); // View içerisinde model datası olarak kullanıcı nesnesini sayfaya gönderdik
		}
		[HttpPost]
		public IActionResult KullaniciDetay(Kullanici kullanici) // post metodunda modelden gelen nesneyi bu şekilde parantez içinde yakalayabiliyoruz
		{
			return View(kullanici); // gelen kullanıcı nesnesini tekrardan ekrana yolla
		}
		public IActionResult AdresDetay()
		{
			Adres adres = new()
			{
				Sehir = "Çankırı", Ilce = "Çerkeş", AcikAdres = "1907 sk. Mo : 21 A"
			};
			return View(adres);
		}
		public IActionResult UyeSayfasi()
		{
			return View();
		}
	}
}

Views/Home/ContactUs.cshtml
@{
	ViewData["Title"] = "İletişim";
}

<h1>İletişim</h1>


<form asp-action="ContactUs">

	<div class="row">
		<div class="col-2">
			@Html.Label("lblAd", "Adınız")
		</div>
		<div class="col-4">
			@Html.TextBox("txtAd", "", "", new { @class = "form-control", required="required" })
		</div>
	</div>

	<div class="row mt-2">
		<div class="col-2">
			@Html.Label("lblSoyad", "Soyadınız")
		</div>
		<div class="col-4">
			@Html.TextBox("txtSoyad", "", "", new { @class = "form-control", required="required" })
		</div>
	</div>

	<div class="row mt-2">
		<div class="col-2">
			@Html.Label("lblTelefon", "Telefon")
		</div>
		<div class="col-4">
			@Html.TextBox("txtTelefon", "", "", new { @class = "form-control", required="required" })
		</div>
	</div>

	<div class="row mt-2">
		<div class="col-2">
			@Html.Label("lblMesaj", "Mesajınız")
		</div>
		<div class="col-4">
			@Html.TextArea("txtMesaj", "", 3, 5, new { @class = "form-control" })
		</div>
	</div>

	<div class="row mt-2">
		<div class="col">
    	<input type="submit" value="Gönder" class="btn btn primary" />
		</div>

	</div>


</form>

Views/Home/Index.cshtml
@{
	ViewData["Title"] = "Home Page";
}

<div class="text-center">
	<h1 class="display-4">Welcome</h1>
	<p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

<h2>
	.NEt Nedir?
</h2>

<p>
	.NET Framework, Microsoft tarafından geliştirilen,
	açık İnternet protokolleri ve standartları üzerine kurulmuş bir
	"uygulama" geliştirme platformu. Daha önce Sun Microsystems tarafından
	geliştirilmiş olan Java platformuna önemli benzerlikler
	göstermektedir. Buradaki uygulama kavramının kapsamı çok geniştir.
</p>

<h2>
	MVC Nedir?
</h2>

<p>
	ASP.NET MVC Framework "Community Technology Preview", 10 Aralık 2007 tarihinde, Microsoft'un ASP.NET için geliştirdiği Model-view-controller iskeletidir. Bu iskelet ile ASP.NET uygulamaları, Model, View ve Controller rollerine bölünerek geliştiriliyor.Model uygulamanın üzerinde duracağı meseleyi temsil ediyor.
</p>

<p>
	ASP.NET MVC Framework dışında asp.net webform teknolojisi ile de web uygulaması geliştirilebiliyor.
</p>

<h2>
	.Net Core Nedir?
</h2>

<p>
	.NET, Windows, Linux ve macOS işletim sistemleri için ücretsiz ve açık kaynaklı, yönetilen bir bilgisayar yazılımı çerçevesidir. .NET Framework'ün platformlar arası halefidir. Proje, öncelikle Microsoft çalışanları tarafından .NET Vakfı aracılığıyla geliştirildi ve MIT Lisansı altında yayınlandı.
</p>

<h3>
	Dependencies
</h3>

<p>
	Asp.Net Mvc uygulamasının çalışması için gerekli alt yapıyı ve paketleri sağlar.
</p>

<h3>
	Properties
</h3>

<p>
	Asp.Net Mvc uygulamasının çalışması için gerekli ayarları tutan .json dosyasının bulunduğu klasör.
</p>

<h3>wwwroot</h3>

<p>
	web uygulamamızda kullanacağımız css, js dosyaları ve bootstrap, jquerry vb kütüphaneleri tutan ayrıca projede kullanacağımız template ve resim, video vb fiziksel dosyaları saklayan klasör.
</p>

Views/MVC01RazorSyntax/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
    Mvc de yorum satırları @ * ve * @ arasına yazılabilir
*@
@{
    // Burası C# kodu yazma alanı. View sayfalarında @ işareti ile c# kodu yazmaya razor syntax ı denir
    string adi = "Alp";
    string soyadi = "Arslan"; // c# değişkeni tanımlayabiliriz.
    string baslik = "MVC01 Razor Syntax";
    string[] isimler = {"Ali", "Veli", "Alp" }; // dizi tanımlayabiliriz
    
}

<h1>
    @baslik
</h1>

<h2>
    Adı : @adi
</h2>

<h3>
    Soyadı : @soyadi
</h3>

<h4>
    isimler
</h4>
@foreach (var ad in isimler)
{
    @ad
    <hr />
}

<hr />

@foreach (var ad in isimler)
{
    
    <h5>
        @ad
    </h5>
}

@for (int i = 0; i < 5; i++)
{
    <h6>
        @i
    </h6>
}

Views/MVC02HtmlAndTagHelpers/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>
	MVC Html ve Tag Helpers Kullanımı
</h1>

<p>
	Mvc ekranda html elementlerin oluşturmak için bize bu helper metotlarıyla yardımcı olur.
</p>

@Html.ActionLink("Anasayfa", "Index", "Home")

@Html.ActionLink("MVC Razor Syntax", "Index", "MVC01RazorSyntax")

<br />

<a href="/Home/Index/25">MVC Html ve Tag Helpers Kullanımı</a>

<br />

<a asp-action="Index" asp-controller="Home" asp-route-id="18">MVC Html ve Tag Helpers Kullanımı</a>

<a asp-action="Index" asp-controller="Home">Anasayfa</a>

<h3>
	Html CheckBox Oluşturma
</h3>
@Html.CheckBox("cbOnay") Kabul Ediyorum

<input id="cbOnay" name="cbOnay" type="checkbox" value="true" />

<h3>
	Html TextBox Oluşturma
</h3>
@Html.TextBox("txtAd")
<input type="text" value="Ekranda veri giriş alanı oluşturur" name="txtSoyad" />

<h3>
	Html Hidden(Gizli Element) Oluşturma
</h3>
@Html.Hidden("GizliElement", "Gizli Element ekranda görünmez kaynak kodunda görünür")

<h3>
	Html Label Oluşturma
</h3>
@Html.Label("lblAd", "Html label elementi")

<h3>
	Html Textarea(çok satırlı veri giriş kutusu) Oluşturma
</h3>
@Html.TextArea("txtAdres", "Html TextArea(çok satırlı veri giriş kutusu) Oluşturma")

<h3>
	Html Password Oluşturma
</h3>
@Html.Password("txtPassword")

<h3>
	Html Helpers ile Form Oluşturma
</h3>
@using (Html.BeginForm())
{
	<h5>
		Kullanıcı Adınız
	</h5>
	@Html.Editor("txtKullaniciAdi")
	<h5>
		Şifreniz
	</h5>
	@Html.Password("txtSifre")
	<br />
	<input type="submit" value="Giriş" />
}
<form action="/MVC02HtmlAndTagHelpers" method="post">
	<h5>
		Kullanıcı Adınız
	</h5>
	<input class="text-box single-line" id="txtKullaniciAdi" name="txtKullaniciAdi" type="text" value="">    <h5>
		Şifreniz
	</h5>
	<input id="txtSifre" name="txtSifre" type="password">
	<br>
	<input type="submit" value="Giriş">
</form>
<h3>
	MVC Tag Helpers Kullanarak Form Oluşturma
</h3>

<form asp-action="Index" asp-controller="MVC02HtmlAndTagHelpers" method="get">
	<input id="ara" name="ara" type="text" placeholder="Aranacak Kelime...">

</form>

<h3>
	Listbox ve Dropdownlist Elementi Kullanımı
</h3>

@{
	var kategoriler = new SelectListItem[]
				{
	 new SelectListItem(){Text = "Bilgisayar"},
	 new SelectListItem(){Text = "Elektronik"},
	 new SelectListItem(){Text = "Telefon"}

				};
	var htmlRawOrnek = "<b>Html Raw İle Ekrana Html İçerik Yazdırma<b>";
}


<h5>
	Listbox
</h5>
@Html.ListBox("lbListe", kategoriler)
<h5>
	DropDownList
</h5>
@Html.DropDownList("lbListe", kategoriler)
<hr />
<h3>
	RadioButton Elementi Kullanımı
</h3>
@Html.RadioButton("rbOnay", "Onaylıyorum") Sözleşmeyi Onaylıyorum

<h3>
	Html Raw İle Ekrana Html İçerik Yazdırma
</h3>

@htmlRawOrnek
<hr />
@Html.Raw(htmlRawOrnek)

Views/MVC03DataTransfer/Index.cshtml
@{

}

<h1>
	MVC de View ve Controller Arasında Veri Gönderimi
</h1>

<h3>
	Controller'dan Gelen Ürün Bilgileri
</h3>

<table class="table table-striped table-hover"> 
	<tr>
		<td>
			Ürün Kategorisi
		</td>
		<td>
			@ViewBag.UrunKategorisi
		</td>
	</tr>
	<tr>
		<td>
			Ürün Adı
		</td>
		<td>
			@ViewData["ÜrünAdi"]
		</td>
	</tr>
	<tr>
		<td>
			Ürün Fiyatı
		</td>
		<td>
			@TempData["UrunFiyatı"]
		</td>
	</tr>
</table>

<hr />

<h2>
	Mvc de Viewdan Controller a Veri Gönderme
</h2>

<h3>
	1-GET Metoduyla Veri Gönderme 
</h3>

<p>
	Html Get metodunda veriler tarayıcı adres çubuğu üzerinden QuerryString yöntemiyle gönderilir.
</p>

<form asp-action="Index" method="get">
	<input type="text" name="Ara" placeholder="Ara.." />
	<button type="submit">Ara</button>
</form>

<h6>
	Aranan Kelime : @ViewBag.GetVerisi
</h6>

<h3>
	2-POST metoduyla veri gönderme
</h3>

@{
	var kategoriler = new SelectListItem[]
				{
	 new SelectListItem(){Text = "Bilgisayar",  Value = "1"},
	 new SelectListItem(){Text = "Elektronik", Value = "2"},
	 new SelectListItem(){Text = "Telefon", Value = "3"}

				};
}

<form asp-action="Index" method="post">
	<div>
		Ürün Adı : @Html.TextBox("text1")
	</div>

	<div>
		Kategorisi : @Html.DropDownList("ddlListe", kategoriler)
	</div>

	<div>
		Durum : @Html.CheckBox("cbOnay")
	</div>
	<input type="submit" value="Gönder" />

</form>

<h3>@ViewBag.Yontem1</h3>
@ViewBag.Mesaj
<hr />
@ViewData.["MesajListe"]
<hr />
@TempData["Tdata"]
<hr />

<h3>@ViewBag.Yontem2</h3>
@ViewBag.Mesaj2
<hr />
@ViewData.["MesajListe2"]
<hr />
@TempData["Tdata2"]

<hr />
<h3>@ViewBag.Yontem3</h3>
@ViewBag.Mesaj3
<hr />
@ViewData.["MesajListe3"]
<hr />
@TempData["Tdata3"]

Views/MVC04ModelBinding/AdresDetay.cshtml
@model Adres
@{
    ViewData["Title"] = "Adres Detay";
}

<h1>Adres Detay</h1>

<form>
	<table>
		<tr>
			<td>Şehir</td>
			<td>
				<input asp-for="Sehir" />
			</td>
		</tr>
		<tr>
			<td>İlçe</td>
			<td>
				<input asp-for="Ilce" />
			</td>
		</tr>
		<tr>
			<td>Açık Adres</td>
			<td>
				<input asp-for="AcikAdres" />
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="submit" value="Gönder" />
			</td>
		</tr>
	</table>
</form>

Views/MVC04ModelBinding/Index.cshtml
@{
}
<h1>
	Model Binding - Model Kullanımı
</h1>

<ol>
	<li>Model klasörüne class ekleyip içine property lerini tanımlıyoruz</li>
	<li>Controller da bir action açıp sayfa oluşturduk</li>
	<li>Sayfada model kullanabilmek için en üstte @@ işareti ve küçük harfle model class adını belirttik</li>
	<li>Sayfada modeli kullanmak için büyük harfle Model yazıp . deyip classını property lerine eriştik</li>
	<li>Sayfada model kullandığımızda hata almamak için controllerdaki get metodunda model class ından bir nesne oluşturup view a yollamalıyız</li>
</ol>

<a asp-action="KullaniciDetay">
	Kullanici Detay sayfasına git
</a>
<a asp-action="AdresDetay">
	Adres Detay sayfasına git
</a>

Views/MVC04ModelBinding/KullaniciDetay.cshtml
@model Kullanici
@{
    ViewData["Title"] = "Kullanici";
}

<h1>Kullanici Bilgileri</h1>



@*
    @Model.Ad
    Sayfada modeli bu şekilde kullandığımızda NullReferenceException: Object reference not set to an instance of an object. hatası alırsak modelimizin için controller da doldurulmamıştır.
*@

<table class="table">
	<tr>
		<td>Ad</td>
		<td>: @Model.Ad</td>
    </tr>
    <tr>
        <td>Soyad</td>
        <td>: @Model.Soyad</td>
    </tr>
    <tr>
        <td>Email</td>
        <td>: @Model.Email</td>
    </tr>
    <tr>
        <td>Kullanici Adı</td>
        <td>: @Model.KullaniciAdi</td>
    </tr>
    <tr>
        <td>Şifre</td>
        <td>: @Model.Sifre/td>
    </tr>
</table>

<h3>
    Kullanıcı Bilgilerini Düzenleme
</h3>

<form asp-action="KullaniciDetay" method="post">
    <table class="table">
	<tr>
		<td>Ad</td>
		<td>: @Html.TextBoxFor(model=>model.Ad)</td>
    </tr>
    <tr>
        <td>Soyad</td>
            <td>:  @Html.TextBoxFor(model=>model.Soyad)</td>
    </tr>
    <tr>
        <td>Email</td>
            <td>:  @Html.TextBoxFor(model=>model.Email)</td>
    </tr>
    <tr>
        <td>Kullanici Adı</td>
            <td>: @Html.TextBoxFor(model=>model.KullaniciAdi)</td>
    </tr>
    <tr>
        <td>Şifre</td>
            <td>: @Html.TextBoxFor(model=>model.Sifre)</td>
    </tr>
		<tr>
			<td></td>
			<td>
				<input type="submit" value="Gönder" />
            </td>
        </tr>
</table>
</form>
<h3>
    asp-for Kullanarak Model Binding
</h3>
<hr />

 <form asp-action="KullaniciDetay">
	<input asp-for="Ad" /><br />
	<input asp-for="Soyad" /><br />
	<input asp-for="Email" /><br />
	<input asp-for="KullaniciAdi" /><br />
	<input asp-for="Sifre" /><br />
	<hr />
	<input type="submit" value="Gönder" />
 </form>

Views/MVC04ModelBinding/UyeSayfasi.cshtml
@model Kullanici
@model Adres
@{
    ViewData["Title"] = "Üye ve Adres Bilgileri";
}

<h1>Üye ve Adres Bilgileri</h1>

@Model.Ad

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - P013AspNetMVCEgitim</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/P013AspNetMVCEgitim.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">P013AspNetMVCEgitim</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Anasayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MVC01RazorSyntax" asp-action="Index">Razor Syntax</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MVC02HtmlAndTagHelpers" asp-action="Index">MVC02HtmlAndTagHelpers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MVC03DataTransfer" asp-action="Index">DataTransfer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MVC04ModelBinding" asp-action="Index">ModelBinding</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Home" asp-action="ContactUs">İletişim</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - P013AspNetMVCEgitim - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>